### ISSUE TITLE
Mod Errors that worked well in 32Bit

### ISSUE THREAD

**Issue by Elperro345** [Steviegt6/Stardew64Installer#30]
I move my mods from the 32bit version to this one (64bit) and 3 mods show errors.
Space core, Walk of life & Placement plus. At least those are the ones that i have found. 
Hopefully it can help in some way.

https://smapi.io/log/13ce466403ff46aeb5addbad247ad2

[SMAPI-latest.txt](https://github.com/Steviegt6/Stardew64Installer/files/6859691/SMAPI-latest.txt)

**Comment by steviegt6** [comment]
Can you isolate the errors in the log for me? The SMAPI log link is invalid, and your log is 4 megabytes of text.

**Comment by Elperro345** [comment]
Yes, sorry! I forgot to say, I have around 290 mods on

SpaceCore | GetLoadEnumeratorMethods: Found 1 transpiler targets, expected 2

Walk Of Life
Mod crashed on entry and might not work correctly. Technical details: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)    at System.Reflection.Assembly.GetTypes()    at Harmony.AccessTools.<>c.<TypeByName>b__1_0(Assembly x)    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)    at Harmony.AccessTools.TypeByName(String name)    at Harmony.AccessTools.Method(String typeColonMethodname, Type[] parameters, Type[] generics)    at TheLion.AwesomeProfessions.CrabPotMachineGetStatePatch.Apply(HarmonyInstance harmony)    at TheLion.AwesomeProfessions.HarmonyPatcher.ApplyAll(IPatch[] patches) in C:\dev\SMAPI Mods\WalkOfLife\Framework\Utility\Professions.cs:line 16    at TheLion.AwesomeProfessions.AwesomeProfessions.Entry(IModHelper helper)    at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase)  Failed loading type 'OptionValue': System.TypeLoadException: Could not load type 'OptionValue' from assembly 'Steamworks.NET, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.  Failed loading type 'OptionValue': System.TypeLoadException: Could not load type 'OptionValue' from assembly 'Steamworks.NET, Version=15.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.

PlacementPlus
Mod crashed on entry and might not work correctly. Technical details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'PlacementPlus.Patches.ReusablePatches_SkipMethod' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Stardew Valley' or one of its dependencies. The system cannot find the file specified.    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)    at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)    at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)    at System.Reflection.Assembly.Load(String assemblyString)    at PlacementPlus.Patches.ReusablePatches_SkipMethod..cctor() in C:\Users\Retr0\Documents\1SHORTCUTS\MODS\Stardew Valley\PlacementPlus\PlacementPlus.cs:line 47    --- End of inner exception stack trace ---    at PlacementPlus.Patches.ReusablePatches_SkipMethod.TargetMethods() in C:\Users\Retr0\Documents\1SHORTCUTS\MODS\Stardew Valley\PlacementPlus\PlacementPlus.cs:line 87    --- End of inner exception stack trace ---    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)    at Harmony.PatchProcessor.RunMethod[S,T](T defaultIfNotExisting, Object[] parameters)    at Harmony.PatchProcessor.PrepareType()    at Harmony.PatchProcessor..ctor(HarmonyInstance instance, Type type, HarmonyMethod attributes)    at Harmony.HarmonyInstance.<PatchAll>b__9_0(Type type)    at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)    at Harmony.HarmonyInstance.PatchAll(Assembly assembly)    at Harmony.HarmonyInstance.PatchAll()    at PlacementPlus.PlacementPlus.Entry(IModHelper helper) in C:\Users\Retr0\Documents\1SHORTCUTS\MODS\Stardew Valley\PlacementPlus\PlacementPlus.cs:line 75    at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase)

**Comment by steviegt6** [comment]
Looks like they're loading the SDV assembly strangely. Likely not an issue I can help with.
Closing this for now, feel free to re-open if you have any reason to.

**Comment by Elperro345** [comment]
Thanks! 
What you think that it may be the problem? the mods themselves not being prepare for 64?

**Comment by steviegt6** [comment]
> 
> 
> Thanks!
> What you think that it may be the problem? the mods themselves not being prepare for 64?

Something like that... probably...
